pri_online_recruitment_system/pors_app/urls.py
from django.urls import path
from . import views

app_name = "pri"

urlpatterns = [
    path('', views.PriAdminDashboard.as_view(), name='dashboard'),
    path('administrator/', views.PriAdmin.as_view(), name='admin'),
    path('client/', views.PriClients.as_view(), name='client'),
    path('client/hired/', views.PriHired.as_view(), name='hired'),
    path('client/jobs/', views.PriJobs.as_view(), name='jobs'),
    path('client/schedules/', views.PriSchedules.as_view(), name='schedules'),
    path('client/requests/', views.PriRequest.as_view(), name='requests'),
    path('applicants/', views.PriApplicants.as_view(), name='applicants'),
    path('applicants/application_form/', views.PriApplicationForm.as_view(), name='application_form'),
    path('applicants/examination/', views.PriExamninations.as_view(), name='examination'),

    #Pri Admin Users

    path('admin/user/sort_admin/', views.pri_admin_users_sort_records, name='sort_admin'),
    path('admin/user/record_limit_admin/', views.pri_admin_users_record_limiter, name="record_limit_admin"),
    path('admin/user/search_admin/', views.pri_admin_users_search_filter, name="search_admin"),
    path('admin/user/paging_admin/', views.pri_admin_users_paging, name="paging_admin"),

    path('admin/user/create/account/', views.pri_admin_users_create_account_form, name="create_account_admin"),
    path('admin/update/profile/<int:id>/', views.pri_admin_update_profile, name='admin_update_profile'),
    path('admin/delete/profile/<int:id>/', views.pri_admin_users_delete_form, name='delete_account_admin'),

    #PRI Admin Clients
    path('admin/clients/create/client/', views.pri_admin_create_clients, name="create_clients"),
    path('admin/clients/edit/client/<int:id>/', views.pri_admin_edit_clients, name="edit_clients"),
    path('admin/clients/delete/client/<int:id>/', views.pri_admin_delete_clients, name="delete_clients"),

    path('admin/clients/sort_clients/', views.pri_admin_client_sort_records, name='sort_clients'),
    path('admin/clients/record_limit_clients/', views.pri_admin_client_record_limiter, name="record_limit_clients"),
    path('admin/clients/search_clients/', views.pri_admin_client_search_filter, name="search_clients"),
    path('admin/clients/paging_clients/', views.pri_admin_client_paging, name="paging_clients"),

    #PRI Admin Request
    path('admin/requests/create/requests/', views.pri_admin_create_requests, name="create_requests"),
    path('admin/requests/edit/requests/<int:id>/', views.pri_admin_edit_requests, name="edit_requests"),
    path('admin/requests/delete/requests/<int:id>/', views.pri_admin_delete_requests, name="delete_requests"),
    path('admin/requests/view/requests/<int:id>/', views.pri_admin_view_requests, name="view_requests"),

    path('admin/requests/sort_requests/', views.pri_admin_requests_sort_records, name='sort_requests'),
    path('admin/requests/record_limit_requests/', views.pri_admin_requests_record_limiter, name="record_limit_requests"),
    path('admin/requests/search_requests/', views.pri_admin_requests_search_filter, name="search_requests"),
    path('admin/requests/paging_requests/', views.pri_admin_requests_paging, name="paging_requests"),

    #PRI Admin Jobs
    path('admin/jobs/create/jobs/<int:id>/', views.pri_admin_create_jobs, name="create_jobs"),
    path('admin/jobs/edit/jobs/<int:id>/', views.pri_admin_edit_jobs, name="edit_jobs"),
    path('admin/jobs/delete/jobs/<int:id>/', views.pri_admin_delete_jobs, name="delete_jobs"),

    path('admin/jobs/sort_jobs/', views.pri_admin_jobs_sort_records, name='sort_jobs'),
    path('admin/jobs/record_limit_jobs/', views.pri_admin_jobs_record_limiter, name="record_limit_jobs"),
    path('admin/jobs/search_jobs/', views.pri_admin_jobs_search_filter, name="search_jobs"),
    path('admin/jobs/paging_jobs/', views.pri_admin_jobs_paging, name="paging_jobs"),

    path('admin/jobs/applicant/<str:key>/', views.PriJobsApplicantsRequests.as_view(), name="applicant_request_jobs"),
    path('admin/jobs/applicant/profile/view/<int:id>/<str:akey>/', views.pri_applicant_profile_view, name="applicant_profile_viewer"),

    #toggle exam
    path('admin/jobs/applicant/exam/<str:key>/<int:id>/', views.pri_jobs_applicant_requests_toggle_exam, name="applicant_request_jobs_toggle_exams"),
    #schedules
    path('admin/jobs/applicant/interview/schedule/<str:key>/<int:id>/', views.pri_jobs_applicant_requests_set_interview_sched, name="applicant_request_jobs_set_interview_sched"),

    #PRI Schedules
    path('admin/schedules/job/request/applicant/toggleexam/<int:id>/', views.pri_schedules_toggle_exam, name="toggle_exams"),

    #PRI Applcaints
    path('admin/applicants/registered/delete/<str:key>/', views.pri_admin_delete_applicants, name="applicant_delete_record"),

    path('admin/applicants/job/request/exam/list/<str:key>/<int:id>/', views.PRIApplicantExamListPage.as_view(), name="applicant_exam_list"),
    path('admin/applicants/job/request/exam/test1/pre_employment/<str:key>/<int:id>/', views.pri_applicant_test1_pre_employment, name="applicant_exam_test1"),
    path('admin/applicants/job/request/exam/test2/simple_english/<str:key>/<int:id>/', views.pri_applicant_test2_simple_english, name="applicant_exam_test2"),
    path('admin/applicants/job/request/exam/test3/essay/<str:key>/<int:id>/', views.pri_applicant_test3_essay, name="applicant_exam_test3"),
    path('admin/applicants/job/request/exam/test3/sct/<str:key>/<int:id>/', views.pri_applicant_test3_sct, name="applicant_exam_test3_sct"),
    path('admin/applicants/job/request/exam/test4/abstract_reasoning/<str:key>/<int:id>/', views.pri_applicant_test4_abstract_reasoning, name="applicant_exam_test4"),
    path('admin/applicants/job/request/exam/ssct/<str:key>/<int:id>/', views.pri_applicant_exam_ssct, name="applicant_exam_scct"),
    path('admin/applicants/job/request/exam/ccat/<str:key>/<int:id>/', views.pri_applicant_exam_ccat, name="applicant_exam_ccat"),
    path('admin/applicants/job/request/exam/arp/<str:key>/<int:id>/', views.pri_applicant_exam_arp, name="applicant_exam_arp"),
    #PRI Applicant Examinations
]

pri_online_recruitment_system/pri_online_recruitment_system/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from pors_app import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('pri_administrator/login/', views.pri_user_login, name="user_login"),
    path('pri_administrator/logout/', auth_views.LogoutView.as_view(), name="logout"),

    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    #FOR APPLICANT SIDE
    path('pri/applicant_side/account/registration', views.pri_applicant_account_registration_page, name='applicant_side_account_registration'),
    path('pri/applicant_side/registration/<str:slug>/', views.pri_applicant_registration_page, name='applicant_side_registration'),
    path('pri/applicant_side/update/profile/<str:slug>/', views.pri_applicant_edit_profile_page, name='applicant_side_update_profile'),
    
    path('pri/applicant_side/job/posts/all/', views.PRIApplicantSideJobPostPageAll.as_view(), name='applicant_side_job_posts_all'),
    path('pri/applicant_side/job/posts/recommended/', views.PRIApplicantSideJobPostPageRecommended.as_view(), name='applicant_side_job_posts_recommended'),
    path('pri/applicant_side/job/posts/search/results/', views.PRIApplicantSideJobPostSearchPage, name='applicant_side_job_posts_search'),
    path('pri/applicant_side/job/posts/request/<int:jv_id>/<int:a_id>/', views.pri_applicant_job_request, name='applicant_side_job_request'),
    path('pri/applicant_side/job/applicant/request/status/ongoing/<int:id>/', views.pri_applicant_job_request_ongoing_status, name='applicant_side_job_request_ongoing_status'),

    path('export/csv/', views.export_users_csv, name="export_users_csv"),
    path('export/xls/', views.export_users_xls, name="export_users_xls"),
    path('export/xlsx/', views.export_users_xlsx, name="export_users_xlsx"),

    path('', include('pors_app.urls')),
    path('admin/', admin.site.urls),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#use to access files and images in static

pri_online_recruitment_system/pors_app/templates/pri_applicant_side/applicant_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>PRI Job Posting Home</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">

  <link href="{% static 'css/main.css' %}" rel="stylesheet">

</head>

<body class="">

  <!-- Navigation -->
  
{% if request.user.is_authenticated  %}
  {% if user %}
    {% if request.user.username == user.username %}
    <nav class="navbar navbar-expand-lg navbar-dark custom-color-header fixed-top">
      <div class="container">
          <a class="navbar-brand" href="#">
            <img class="rounded-circle" src="{% static 'images\pri_logo.jpg' %}" alt="" height="42" width="42">
          </a>
          <a class="navbar-brand" href="#">PRI Job Posts</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'applicant_side_job_posts_all' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item dropdown no-arrow">
                  <a class="nav-link dropdown-toggle" href="#" id="userDropdownStatus" role="button" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                      <span class="">Status</span> 
                  </a>
                  {% if profile %} 
                  {% for p in profile %}
                  
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdownStatus">
                      <a class="dropdown-item" data-url="{% url 'applicant_side_job_request_ongoing_status' p.id %}" href="#" id="menu-show-job-request-status">On going job request</a> 
                      <a class="dropdown-item" href="#">Job hired</a>
                  </div>
                  {% endfor %}
                  {% endif %}
              </li> 
              <!-- Account Dropdown -->
              <li class="nav-item dropdown no-arrow">
                  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                      <span class="">({{request.user.username}})</span> 
                  </a>
      
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    {% if profile %}
                    <a class="dropdown-item" href="{% url 'applicant_side_update_profile' request.user.username %}">Update Profile</a> 
                    {% endif %} 
                      <a class="dropdown-item" href="{% url 'password_change' %}">Update Password</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'logout' %}" >Logout</a>
                  </div>
              </li>

            </ul>
          </div>
        </div>
      </nav>
      
      <!-- Page Content -->
      <div class="container"> 
          {% if not profile %}
          <div class="container" style="padding-top: 4%;">
              <div class="card mb-4">
                  <div class="card-body">
                    <h2 class="card-title text-center">Set up your profile first!</h2>
                    <p class="card-text text-center">Let the profile work for you click <a href="{% url 'applicant_side_registration' request.user.username %}">Here</a></p>
                  </div>
                </div>     
          </div>
          {% else %}
            {% block body_block %}
            {% endblock body_block %}
          {% endif %}
      </div>
      <!-- /.container -->
    
      <!-- Footer -->
      <footer class="py-5 custom-color-header">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; PRI Hiring System 2019</p>
        </div>
        <!-- /.container -->
      </footer>


        

    {% endif %}
  {% endif %}
{% endif %}  

<div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>

<div class="modal fade" id="modal-form-large" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/applicant_index.js' %}"></script>


</body>

</html>

pri_online_recruitment_system/pors_app/templates/pri_applicant_side/applicant_job_post_page.html
{% extends 'pri_applicant_side/applicant_base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">Job Posts
          <small>vacancies</small>
        </h1>
        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">

          <li class="page-item {% if current_post == 'all' %} active {% endif %}">
            <a class="page-link" href="{% url 'applicant_side_job_posts_all' %}">&larr; All Jobs</a>
          </li>
          <li class="page-item {% if current_post == 'recommended' %} active {% endif %}">
            <a class="page-link" href="{% url 'applicant_side_job_posts_recommended' %}">Recommended &rarr;</a>
          </li>

        </ul>

        <!-- Blog Post -->
        {% include 'pri_applicant_side/applicant_row_posts.html' %}

      
      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <form class="" action="{% url 'applicant_side_job_posts_search' %}" method="GET">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for Job Position..." aria-label="Search" name="search_term" value="{{ search_term }}" required>
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="Submit">Go!</button>
                </span>
              </div>
            </form>
          </div>
        </div>

        <!-- Categories Widget -->
        <!-- <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div> -->

        <!-- Side Widget -->
        <!-- <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div> -->

      </div>

    </div>
    <!-- /.row -->
{% endblock body_block %}

pri_online_recruitment_system/pors_app/templates/pri_applicant_side/applicant_job_request.html
{% load crispy_forms_tags %}

<form method="POST" data-url="{% url 'applicant_side_job_request' job_vacancy.id applicant.id %}" action="" class="applicant-job-request-form">
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Do you want to applying for this job?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>

    <div class="modal-body"> 
        <p class="lead">After you apply for this job you will take the exam and receive <strong>E-mail notification</strong> to confirm your hired.</p> 
        
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success">Apply</button>
    </div>


</form>

pri_online_recruitment_system/pors_app/templates/pri_applicant_side/applicant_job_request_ongoing_status.html
{% load crispy_forms_tags %}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Applicant Status</h5>
    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>

<div class="modal-body">
    <h5 class="text-center">Job request status</h5>
    <table class="table table-striped" id="tblGrid">
        <thead id="tblHead">
            <tr>
                <th style="width: 20%;" class="text-center">Company</th>
                <th style="width: 20%;" class="text-center">Job Title</th>
                <th style="width: 10%;" class="text-center">Status</th>
                <th style="width: 25%;" class="text-center">Date Applied</th>
                <th style="width: 5%;" class="text-center">Examinations</th>
                <th style="width: 30%;" class="text-center">Interview Date</th>
            </tr>
        </thead>
        <tbody>
            {% for job in job_request %}
            <tr>
                <td class="text-center">{{ job.job_vacancy_applied.client_request.requested_client.client_company_name }}</td>
                <td class="text-center">{{ job.job_vacancy_applied.job_title }}</td>
                <td class="text-center"><span class="badge badge-danger">On going</span></td>
                <td class="text-center">{{ job.date_applied }}</td>
                <td class="text-center">
                    <button
                    {% if not job.take_exam %} disabled {% endif %} type="button" onclick="window.location.href = '{% url 'pri:applicant_exam_list' profile.secure_key_id job.id %}';"
                        class="d-none d-sm-inline-block btn btn-sm btn-info shadow-sm show-exam-page"
                        data-toggle="tooltip" data-placement="top" title="Take Exam">
                        <span class="fas fa-clipboard-list"></span>
                    </button>
                </td>
                <td class="text-center">{{ job.interview_date }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6" class="text-center bg-warning">No Records!</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

pri_online_recruitment_system/pors_app/templates/pri_applicant_side/applicant_row_posts.html
{% load staticfiles %}
{% load humanize%}
<!-- https://simpleisbetterthancomplex.com/tips/2016/05/09/django-tip-2-humanize.html -->
{% for job in job_vacancies %}
<!-- Blog Post -->
<div class="card mb-4">
  <img class="card-img-top" src="
  {% if job.client_request.requested_client.client_company_logo %}
  {{ job.client_request.requested_client.client_company_logo.url }}
  {% else %}
  {% static 'images\750x300.png' %}
  {% endif %}
  " alt="Card image cap" width="750" height="300">
  <div class="card-body">
    <h2 class="card-title">{{ job.job_title }}</h2>
     <ul class="list-unstyled" style="padding-left: 10px">
        <li><span class="text-secondary"><i class="fas fa-search-location"></i></span> <span style="color: #acacac; font-size: 10pt; text-align: left;">Location:</span> <span style="font-size: 10pt; text-align: left;">{{ job.client_request.requested_client.client_location }}</span></li>
        <li><span class="text-secondary"><i class="fas fa-money-bill"></i></span> <span style="color: #acacac; font-size: 10pt; text-align: left;">Salary:</span> <span style="font-size: 10pt; text-align: left;">{{ job.job_salary|intcomma }}</span></li>
        <li><span class="text-secondary"><i class="fas fa-business-time"></i></span> <span style="color: #acacac; font-size: 10pt; text-align: left;">Min. exp:</span> <span style="font-size: 10pt; text-align: left;">{{ job.job_minimum_experience }}</span></li>
     </ul>
    <p class="card-text">{{ job.job_description }}</p>

    <!-- Card Content - Collapse -->
    <div class="collapse-hide collapse hide" id="collapseCard">
      <h5 class="card-title">Company Overview</h5>
      <p class="card-text">{{ job.job_company_overview }}</p>

      <h5 class="card-title">Specialization</h5>
      <ul>
        <li><p class="card-text">{{ job.job_specialization }}</p></li>
      </ul>

      <h5 class="card-title">Job Qualifications</h5>
      <ul>
      {% for qualifications in job.job_vacancy_jq_fk.all %}
       <li>{{ qualifications }}</li>
      {% empty %}
       <li>No qualifications defined.</li>
      {% endfor %}
      </ul>

      <h5 class="card-title">Job Responsibilities</h5>
      <ul>
      {% for responsibilities in job.job_vacancy_jr_fk.all %}
       <li>{{ responsibilities }}</li>
      {% empty %}
       <li>No responsibilities defined.</li>
      {% endfor %}
      </ul>
      <div class="dropdown-divider"></div>
    </div>

    <a href="#collapseCard" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCard" class="btn btn-primary">Read More &rarr;</a>
 
    {% if profile %}
    {% for p in profile %}
        <button type="button" data-url="{% url 'applicant_side_job_request' job.id p.id %}" class="btn btn-success show-apply-form" data-toggle="tooltip" data-placement="top" title="Apply"> 
          Apply
          <i class="fas fa-clipboard-check"></i>
      </button>
    {% endfor %}

    {% endif %}
	

  </div>

  <div class="card-footer">
    <div style="text-align:left;">
      Posted on {{ job.client_request.data_requested }} by
      <a href="#">PRI</a>
      <span style="float:right;">
           Deadline: <span class="badge badge-danger">{{ job.job_deadline }}</span>
      </span>
    </div>
  </div>
</div>
{% empty %}
<div class="card mb-4">
  <div class="card-body">
    <h2 class="card-title text-center">No Job Posted Yet!</h2>
    <p class="card-text text-center">PRI will post job vacancies so keep in touch!</p>
  </div>
</div>

{% endfor %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>
$(document).ready(function(){
    //var count = $("div[class*='collapse hide']").length;
     $('.btn-primary').each(function(i){
        var y = 0;
        //set new arial controls
        $(this).attr('aria-controls', 'collapseCard' + (y++));

        //set new href
        var new_href = $(this).attr('href', '#collapseCard'+(i++));


        // get / check href
        var href = $(this).attr('href');
        console.log("a: "+href);
    });

    $("div .collapse-hide").each(function(x){
        //Old ID
        var i = $(this).attr('id');

        //New ID
        var change_id = $(this).attr('id', 'collapseCard' + (x++));
        //Check New ID
        var new_i = $(this).attr('id');
        console.log("div: "+new_i);
    });

});
</script>

pri_online_recruitment_system/pors_app/templates/pri_applicant_side/application_registrationOriginal.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<!-- https://codepen.io/atakan/pen/gqbIz -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/applicant.css' %}">
</head>

<body>
    <form action="" id="msform">
        <!-- progress bar -->
        <ul id="progressbar">
            <li class="active">
                Account Setup
            </li>
            <li>Social Profiles</li>
            <li>Personal Details</li>
        </ul>

        <!-- field sets --> 

        <fieldset>
            <h2 class="fs-title">Create your account</h2>
            <h3 class="fs-subtitle">This is step 1</h3>
            <input type="email" name="email" placeholder="Email" />
            <input type="password" name="pass" placeholder="Password" />
            <input type="password" name="cpass" placeholder="Confirm Password" />
            <input type="button" name="next" class="next action-button" value="Next">
        </fieldset>

        <fieldset>
            <h2 class="fs-title">Social Profiles</h2>
            <h3 class="fs-subtitle">Your presence on the social network</h3>
            <input type="text" name="twitter" id="" placeholder="Twitter" />
            <input type="text" name="facebook" id="" placeholder="Facebook" />
            <input type="text" name="gplus" id="" placeholder="Google Plus" />
            <input type="button" name="previous" id="" class="previous action-button" value="Previous" />
            <input type="button" name="next" class="next action-button" value="Next">
        </fieldset>

        <fieldset>
            <h2 class="fs-title">Personal Details</h2>
            <h3 class="fs-subtitle">We will never sell it</h3>
            <input type="text" name="fname" placeholder="First Name" />
            <input type="text" name="lname" placeholder="Last Name" />
            <input type="text" name="phone" placeholder="Phone" />
            <textarea name="address" placeholder="Address"></textarea>
            <input type="button" name="previous" class="previous action-button" value="Previous" />
            <input type="submit" name="submit" class="submit action-button" value="Submit" />
        </fieldset>

    </form>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/applicant.js' %}" async defer></script>

</body>

</html>