pri_online_recruitment_system/pors_app/urls.py
from django.urls import path
from . import views

app_name = "pri"

urlpatterns = [
    path('', views.PriAdminDashboard.as_view(), name='dashboard'),
    path('administrator/', views.PriAdmin.as_view(), name='admin'),
    path('client/', views.PriClients.as_view(), name='client'),
    path('client/hired/', views.PriHired.as_view(), name='hired'),
    path('client/jobs/', views.PriJobs.as_view(), name='jobs'),
    path('client/schedules/', views.PriSchedules.as_view(), name='schedules'),
    path('client/requests/', views.PriRequest.as_view(), name='requests'),
    path('applicants/', views.PriApplicants.as_view(), name='applicants'),
    path('applicants/application_form/', views.PriApplicationForm.as_view(), name='application_form'),
    path('applicants/examination/', views.PriExamninations.as_view(), name='examination'),

    #Pri Admin Users

    path('admin/user/sort_admin/', views.pri_admin_users_sort_records, name='sort_admin'),
    path('admin/user/record_limit_admin/', views.pri_admin_users_record_limiter, name="record_limit_admin"),
    path('admin/user/search_admin/', views.pri_admin_users_search_filter, name="search_admin"),
    path('admin/user/paging_admin/', views.pri_admin_users_paging, name="paging_admin"),

    path('admin/user/create/account/', views.pri_admin_users_create_account_form, name="create_account_admin"),
    path('admin/update/profile/<int:id>/', views.pri_admin_update_profile, name='admin_update_profile'),
    path('admin/delete/profile/<int:id>/', views.pri_admin_users_delete_form, name='delete_account_admin'),

    #PRI Admin Clients
    path('admin/clients/create/client/', views.pri_admin_create_clients, name="create_clients"),
    path('admin/clients/edit/client/<int:id>/', views.pri_admin_edit_clients, name="edit_clients"),
    path('admin/clients/delete/client/<int:id>/', views.pri_admin_delete_clients, name="delete_clients"),

    path('admin/clients/sort_clients/', views.pri_admin_client_sort_records, name='sort_clients'),
    path('admin/clients/record_limit_clients/', views.pri_admin_client_record_limiter, name="record_limit_clients"),
    path('admin/clients/search_clients/', views.pri_admin_client_search_filter, name="search_clients"),
    path('admin/clients/paging_clients/', views.pri_admin_client_paging, name="paging_clients"),

    #PRI Admin Request
    path('admin/requests/create/requests/', views.pri_admin_create_requests, name="create_requests"),
    path('admin/requests/edit/requests/<int:id>/', views.pri_admin_edit_requests, name="edit_requests"),
    path('admin/requests/delete/requests/<int:id>/', views.pri_admin_delete_requests, name="delete_requests"),
    path('admin/requests/view/requests/<int:id>/', views.pri_admin_view_requests, name="view_requests"),

    path('admin/requests/sort_requests/', views.pri_admin_requests_sort_records, name='sort_requests'),
    path('admin/requests/record_limit_requests/', views.pri_admin_requests_record_limiter, name="record_limit_requests"),
    path('admin/requests/search_requests/', views.pri_admin_requests_search_filter, name="search_requests"),
    path('admin/requests/paging_requests/', views.pri_admin_requests_paging, name="paging_requests"),

    #PRI Admin Jobs
    path('admin/jobs/create/jobs/<int:id>/', views.pri_admin_create_jobs, name="create_jobs"),
    path('admin/jobs/edit/jobs/<int:id>/', views.pri_admin_edit_jobs, name="edit_jobs"),
    path('admin/jobs/delete/jobs/<int:id>/', views.pri_admin_delete_jobs, name="delete_jobs"),

    path('admin/jobs/sort_jobs/', views.pri_admin_jobs_sort_records, name='sort_jobs'),
    path('admin/jobs/record_limit_jobs/', views.pri_admin_jobs_record_limiter, name="record_limit_jobs"),
    path('admin/jobs/search_jobs/', views.pri_admin_jobs_search_filter, name="search_jobs"),
    path('admin/jobs/paging_jobs/', views.pri_admin_jobs_paging, name="paging_jobs"),

    path('admin/jobs/applicant/<str:key>/', views.PriJobsApplicantsRequests.as_view(), name="applicant_request_jobs"),
    path('admin/jobs/applicant/profile/view/<int:id>/<str:akey>/', views.pri_applicant_profile_view, name="applicant_profile_viewer"),

    #toggle exam
    path('admin/jobs/applicant/exam/<str:key>/<int:id>/', views.pri_jobs_applicant_requests_toggle_exam, name="applicant_request_jobs_toggle_exams"),
    #schedules
    path('admin/jobs/applicant/interview/schedule/<str:key>/<int:id>/', views.pri_jobs_applicant_requests_set_interview_sched, name="applicant_request_jobs_set_interview_sched"),

    #PRI Schedules
    path('admin/schedules/job/request/applicant/toggleexam/<int:id>/', views.pri_schedules_toggle_exam, name="toggle_exams"),

    #PRI Applcaints
    path('admin/applicants/registered/delete/<str:key>/', views.pri_admin_delete_applicants, name="applicant_delete_record"),

    path('admin/applicants/job/request/exam/list/<str:key>/<int:id>/', views.PRIApplicantExamListPage.as_view(), name="applicant_exam_list"),
    path('admin/applicants/job/request/exam/test1/pre_employment/<str:key>/<int:id>/', views.pri_applicant_test1_pre_employment, name="applicant_exam_test1"),
    path('admin/applicants/job/request/exam/test2/simple_english/<str:key>/<int:id>/', views.pri_applicant_test2_simple_english, name="applicant_exam_test2"),
    path('admin/applicants/job/request/exam/test3/essay/<str:key>/<int:id>/', views.pri_applicant_test3_essay, name="applicant_exam_test3"),
    path('admin/applicants/job/request/exam/test3/sct/<str:key>/<int:id>/', views.pri_applicant_test3_sct, name="applicant_exam_test3_sct"),
    path('admin/applicants/job/request/exam/test4/abstract_reasoning/<str:key>/<int:id>/', views.pri_applicant_test4_abstract_reasoning, name="applicant_exam_test4"),
    path('admin/applicants/job/request/exam/ssct/<str:key>/<int:id>/', views.pri_applicant_exam_ssct, name="applicant_exam_scct"),
    path('admin/applicants/job/request/exam/ccat/<str:key>/<int:id>/', views.pri_applicant_exam_ccat, name="applicant_exam_ccat"),
    path('admin/applicants/job/request/exam/arp/<str:key>/<int:id>/', views.pri_applicant_exam_arp, name="applicant_exam_arp"),
    #PRI Applicant Examinations
]

pri_online_recruitment_system/pri_online_recruitment_system/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from pors_app import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('pri_administrator/login/', views.pri_user_login, name="user_login"),
    path('pri_administrator/logout/', auth_views.LogoutView.as_view(), name="logout"),

    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    #FOR APPLICANT SIDE
    path('pri/applicant_side/account/registration', views.pri_applicant_account_registration_page, name='applicant_side_account_registration'),
    path('pri/applicant_side/registration/<str:slug>/', views.pri_applicant_registration_page, name='applicant_side_registration'),
    path('pri/applicant_side/update/profile/<str:slug>/', views.pri_applicant_edit_profile_page, name='applicant_side_update_profile'),
    
    path('pri/applicant_side/job/posts/all/', views.PRIApplicantSideJobPostPageAll.as_view(), name='applicant_side_job_posts_all'),
    path('pri/applicant_side/job/posts/recommended/', views.PRIApplicantSideJobPostPageRecommended.as_view(), name='applicant_side_job_posts_recommended'),
    path('pri/applicant_side/job/posts/search/results/', views.PRIApplicantSideJobPostSearchPage, name='applicant_side_job_posts_search'),
    path('pri/applicant_side/job/posts/request/<int:jv_id>/<int:a_id>/', views.pri_applicant_job_request, name='applicant_side_job_request'),
    path('pri/applicant_side/job/applicant/request/status/ongoing/<int:id>/', views.pri_applicant_job_request_ongoing_status, name='applicant_side_job_request_ongoing_status'),

    path('export/csv/', views.export_users_csv, name="export_users_csv"),
    path('export/xls/', views.export_users_xls, name="export_users_xls"),
    path('export/xlsx/', views.export_users_xlsx, name="export_users_xlsx"),

    path('', include('pors_app.urls')),
    path('admin/', admin.site.urls),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#use to access files and images in static

pri_online_recruitment_system/pors_app/templates/pri_admin/tables/pri_admin_applicants_table.html
{% load staticfiles %}
{% for applicant in applicants %}
<tr>
    <td align="center">
        <img class="img-profile rounded-circle" src="
        {% if applicant.image %}
        {{ applicant.image.url }}
        {% else %}
        {% static 'images\Administrator Male_48px.png' %}
        {% endif %}" width="50" height="50">
    </td>
    <td>{{applicant.user.username }}</td>
    <td>{{applicant.lname}}, {{ applicant.fname}} {{ applicant.lname }}</td>
    <td>
        {% if applicant.cv %}
        <!-- https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons -->
        <a href="{{applicant.cv.url}}" download>
            <span title="Download Curriculum Vitae" class="fas fa-file-download fa-2x"></span>
        </a>
        {% endif %}
    </td>
    <td>{{ applicant.mobile_no }}</td>
    <td>{{ applicant.user.email }}</td>
    <td>
        <button type="button" data-url="{% url 'pri:applicant_delete_record' applicant.secure_key_id %}"
            class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm show-delete-applicant-data"
            data-toggle="tooltip" data-placement="top" title="Delete Applicant">
            <span class="fas fa-trash-alt"></span>
        </button>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="6" class="text-center bg-warning">No Records!</td>
</tr>
{% endfor %}

pri_online_recruitment_system/pors_app/templates/pri_admin/tables/pri_admin_clients_table.html
{% load staticfiles %}
{% for record in query %}
<tr>
    <td class="text-center">{{ record.id }}</td>
    <td align="center"> <img class="img-profile rounded-circle" src="
    {% if record.client_company_logo %}
    {{ record.client_company_logo.url }}
    {% else %}
    {% static 'images\Administrator Male_48px.png' %}
    {% endif %}" width="50" height="50">
    </td>
    <td class="text-center">{{ record.client_company_name }}</td>
    <td class="text-center">{{ record.client_user.last_name }}, {{ record.client_user.middle_name }} {{ record.client_user.first_name }}</td>
    <td class="text-center">{{ record.client_location }}</td>
    <td class="text-center">{{ record.contact_person }}</td>
    <td class="text-center">{{ record.contact_mobile_no }}</td>
    <td class="text-center">{{ record.client_user.user.email }}</td>

    <td align="center">
        <div class="d-md-flex align-items-center justify-content-between mb-4">
            <button type="button" data-url="{% url 'pri:edit_clients' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm show-form-edit-client" data-toggle="tooltip" data-placement="top" title="Edit">
                <span class="fas fa-pencil-alt fa-sm text-black-50"></span>
            </button>

            <button type="button" data-url="{% url 'pri:delete_clients' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm show-form-delete-client" data-toggle="tooltip" data-placement="top" title="Delete">
                <span class="fas fa-trash-alt fa-sm text-white-50"></span>
            </button>

        </div>

    </td>
</tr>
{% empty %}
<tr>
    <td colspan="9" class="text-center bg-warning">No Records!</td>
</tr>
{% endfor %}

pri_online_recruitment_system/pors_app/templates/pri_admin/tables/pri_admin_jobs_applicant_request_table.html
{% load staticfiles %}
{% for job in job_requests %}
<tr>
    <td align="center">
            <img class="img-profile rounded-circle" src="
            {% if job.applying_applicant.image %}
            {{ job.applying_applicant.image.url }}
            {% else %}
            {% static 'images\Administrator Male_48px.png' %}
            {% endif %}" width="50" height="50">
    </td>
    <td><a href="{% url 'pri:applicant_profile_viewer' job_vacancies.id job.applying_applicant.secure_key_id %}" data-toggle="tooltip" title="View Applicant Profile">{{job.applying_applicant.lname}}, {{ job.applying_applicant.fname}} {{ job.applying_applicant.lname }}</a></td>
    <td>
        {% if job.applying_applicant.cv %}
         <!-- https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons -->
         <a href="{{job.applying_applicant.cv.url}}" download>
                <span title="Download Curriculum Vitae" class="fas fa-file-download fa-2x"></span>
         </a>
        {% endif %}
    </td>
    <td>{{ job.applying_applicant.mobile_no }}</td>
    <td>{{ job.applying_applicant.user.email }}</td>
    <td> <span class="badge badge-danger">On going </span></td>
    <td>{{ job.date_applied }}</td>
    <td><span class="badge badge-info">{{job.take_exam}} </span>
        <!-- Rounded switch -->
        <label class="switch">
            <input type="checkbox" data-url="{% url 'pri:applicant_request_jobs_toggle_exams' job_vacancies.secure_id job.id %}" 
            {% if job.take_exam %}            
            checked
            {% endif %}>
            <span class="slider round"></span>
        </label>
    </td>
    <td> 
            <input data-url="{% url 'pri:applicant_request_jobs_set_interview_sched' job_vacancies.secure_id job.id %}" type="text" class="form-control set-schedule-interview" readonly 
            {% if job.interview_date %}
            value="{{ job.interview_date}}"
            {% else %}
            value=""
            {% endif %}            
            >

        <!-- <button type="button" data-url=""
            class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm set-interview-schedule"
            data-toggle="tooltip" data-placement="top" title="Set Schedule">
            <span class="fa fa-calendar"></span>
        </button> --> 
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="9" class="text-center bg-warning">No Records!</td>
</tr>
{% endfor %}

 

pri_online_recruitment_system/pors_app/templates/pri_admin/tables/pri_admin_jobs_table.html
{% load staticfiles %}
<!--https://docs.djangoproject.com/en/dev/ref/contrib/humanize/#ref-contrib-humanize-->
{% load humanize %}
{% for record in query %}
<tr>
    <td class="text-center">{{ record.id }}</td>
    <td class="text-center">{{ record.client_request.requested_client.client_company_name }}</td>
    <td class="text-center">{{ record.job_title }}</td>
    <td class="text-center">{{ record.job_category }}</td>
    <td class="text-center">{{ record.job_specialization }}</td>
    <!--https://docs.djangoproject.com/en/dev/ref/contrib/humanize/#ref-contrib-humanize-->
    <td class="text-center">{{ record.job_minimum_experience }}</td>
    <td class="text-center">&#8369; {{ record.job_salary|intcomma }}</td>
    <td class="text-center"><span class="badge badge-danger">{{ record.job_deadline }}</span></td>

    <td align="center">
        <div class="d-md-flex align-items-center justify-content-between mb-4">
            <button type="button" data-url="{% url 'pri:edit_jobs' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm show-form-edit-jobs" data-toggle="tooltip" data-placement="top" title="Edit">
                <span class="fas fa-pencil-alt fa-sm text-black-50"></span>
            </button>

            <button type="button" data-url="{% url 'pri:delete_jobs' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm show-form-delete-jobs" data-toggle="tooltip" data-placement="top" title="Delete">
                <span class="fas fa-trash-alt fa-sm text-white-50"></span>
            </button>

            <button type="button" data-url="{% url 'pri:applicant_request_jobs' record.secure_id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm show-applicant-requests" data-toggle="tooltip" data-placement="top" title="Applicants">
                <span class="fas fa-users text-white-50"></span> 
            </button>

            
      
        </div>

    </td>
</tr>
{% empty %}
<tr>
    <td colspan="9" class="text-center bg-warning">No Records!</td>
</tr>
{% endfor %}

pri_online_recruitment_system/pors_app/templates/pri_admin/tables/pri_admin_requests_table.html
{% load staticfiles %}


{% for record in query %}
<tr
    {% if not record.seen_by_admin %}
        style="font-weight:bold;"
    {% endif %}
>

    <td class="text-center">{{ record.id }}</td>
    <td class="text-center">{{ record.requested_client }}</td>
    <td class="text-center" >
          {{ record.content }}
    </td>
    <td class="text-center">
        {% if record.status == 'Completed' %}
            <span class="badge badge-success">{{ record.status }}</span>
        {% elif record.status == 'Started' %}
            <span class="badge badge-info">{{ record.status }}</span>
        {% elif record.status == 'Deadline' %}
            <span class="badge badge-warning">{{ record.status }}</span>
        {% elif record.status == 'On Going' %}
            <span class="badge badge-primary">{{ record.status }}</span>
        {% elif record.status == 'Failed' %}
            <span class="badge badge-danger">{{ record.status }}</span>
        {% endif %}
    </td>
    <td class="text-center">
        {% if not record.seen_by_admin %}
            <span class="badge badge-danger">New!</span>
        {% endif %}
        {{ record.data_requested }}
    </td>
    <td align="center">
        <div class="d-md-flex align-items-center justify-content-between mb-4">
            <button type="button" data-url="{% url 'pri:edit_requests' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm show-form-edit-requests" data-toggle="tooltip" data-placement="top" title="Edit">
                <span class="fas fa-pencil-alt fa-sm text-black-50"></span>
            </button>

            <button type="button" data-url="{% url 'pri:delete_requests' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm show-form-delete-requests" data-toggle="tooltip" data-placement="top" title="Delete">
                <span class="fas fa-trash-alt fa-sm text-white-50"></span>
            </button>
            <button type="button" data-url="{% url 'pri:view_requests' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-info shadow-sm show-form-view-requests" data-toggle="tooltip" data-placement="top" title="View">
                <span class="fas fa-eye fa-sm text-white-50"></span>
            </button>
           <button type="button" data-url="{% url 'pri:create_jobs' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm show-form-create-job-vacancy-requests" data-toggle="tooltip" data-placement="top" title="Create Job Vacancy">
                <span class="fas fa-briefcase fa-sm text-white-50"></span>
            </button>


        </div>

    </td>
</tr>
{% empty %}
<tr>
    <td colspan="9" class="text-center bg-warning">No Records!</td>
</tr>
{% endfor %}

pri_online_recruitment_system/pors_app/templates/pri_admin/tables/pri_admin_schedules_tables.html
{% for applicant_request in job_requests %}
<tr>
    <td>{{ applicant_request.job_vacancy_applied.client_request.requested_client.client_company_name }}</td>
    <td>{{ applicant_request.job_vacancy_applied.job_title }}</td>
    <td>{{ applicant_request.applying_applicant.lname }}, {{ applicant_request.applying_applicant.fname }} {{ applicant_request.applying_applicant.mname }}.</td>
    <td><span class="badge badge-danger">On going</span></td>
    <td>{{applicant_request.date_applied}}</td>
    <td>
        <span class="badge badge-info">{{applicant_request.take_exam}} </span>
    
        <button type="button" data-url="{% url 'pri:toggle_exams' applicant_request.id %}"
            class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm toogle-applicant-exam"
            data-toggle="tooltip" data-placement="top" title="Enable to take the exam">
            {% if applicant_request.take_exam %}
            <i class="fas fa-toggle-off "></i>
            {% else %}
            <i class="fas fa-toggle-on "></i>
            {% endif %}            
        </button>
    </td>
    <td>{{applicant_request.interview_date}}
 
        <button type="button" data-url=""
        class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm set-interview-schedule"
        data-toggle="tooltip" data-placement="top" title="Delete Applicant">
        <span class="fas fa-trash-alt"></span>
    </button>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="7" class="text-center bg-warning">No Records!</td>
</tr>
{% endfor %}

pri_online_recruitment_system/pors_app/templates/pri_admin/tables/pri_admin_users_table.html
{% load staticfiles %}
{% for record in query %}
<tr>
    <td class="text-center">{{ record.id }}</td>
    <td align="center"> <img class="img-profile rounded-circle" src="
    {% if record.image %}
    {{ record.image.url }}
    {% else %}
    {% static 'images\Administrator Male_48px.png' %}
    {% endif %}" width="50" height="50">
    </td>

    <td class="text-center">{{ record.last_name }}, {{ record.middle_name }} {{ record.first_name }}</td>
    <td class="text-center">{{ record.user.email }}</td>
    <td class="text-center">{{ record.contact }}</td>
    <td class="text-center">{{ record.position }}</td>
    <td class="text-center">{{ record.department }}</td>
    <td class="text-center">
        {% if record.level == 'Administrator' %}
            <span class="badge badge-success">{{ record.level }}</span>
        {% elif record.level == 'Sub Admin' %}
            <span class="badge badge-info">{{ record.level }}</span>
        {% elif record.level == 'Employee' %}
            <span class="badge badge-warning">{{ record.level }}</span>
        {% elif record.level == 'Client' %}
            <span class="badge badge-primary">{{ record.level }}</span>
        {% elif record.level == 'Applicant' %}
            <span class="badge badge-danger">{{ record.level }}</span>
        {% endif %}
    </td>
    <td align="center">
        <div class="d-md-flex align-items-center justify-content-between mb-4">
            <button type="button" data-url="{% url 'pri:admin_update_profile' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm show-form-edit-admin" data-toggle="tooltip" data-placement="top" title="Edit">
                <span class="fas fa-pencil-alt fa-sm text-black-50"></span>
            </button>

            <button type="button" data-url="{% url 'pri:delete_account_admin' record.id %}"
                    class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm show-form-delete-admin" data-toggle="tooltip" data-placement="top" title="Delete">
                <span class="fas fa-trash-alt fa-sm text-white-50"></span>
            </button>

            <button type="button" data-url="#"
                    class="d-none d-sm-inline-block btn btn-sm btn-info shadow-sm show-payroll-employee-form" data-toggle="tooltip" data-placement="top" title="Permission">
                <span class="fas fa-award  text-white-50"></span>

            </button>
        </div>

    </td>
</tr>
{% empty %}
<tr>
    <td colspan="9" class="text-center bg-warning">No Records!</td>
</tr>
{% endfor %}