pri_online_recruitment_system/pors_app/urls.py
from django.urls import path
from . import views

app_name = "pri"

urlpatterns = [
    path('', views.PriAdminDashboard.as_view(), name='dashboard'),
    path('administrator/', views.PriAdmin.as_view(), name='admin'),
    path('client/', views.PriClients.as_view(), name='client'),
    path('client/hired/', views.PriHired.as_view(), name='hired'),
    path('client/jobs/', views.PriJobs.as_view(), name='jobs'),
    path('client/schedules/', views.PriSchedules.as_view(), name='schedules'),
    path('client/requests/', views.PriRequest.as_view(), name='requests'),
    path('applicants/', views.PriApplicants.as_view(), name='applicants'),
    path('applicants/application_form/', views.PriApplicationForm.as_view(), name='application_form'),
    path('applicants/examination/', views.PriExamninations.as_view(), name='examination'),

    #Pri Admin Users

    path('admin/user/sort_admin/', views.pri_admin_users_sort_records, name='sort_admin'),
    path('admin/user/record_limit_admin/', views.pri_admin_users_record_limiter, name="record_limit_admin"),
    path('admin/user/search_admin/', views.pri_admin_users_search_filter, name="search_admin"),
    path('admin/user/paging_admin/', views.pri_admin_users_paging, name="paging_admin"),

    path('admin/user/create/account/', views.pri_admin_users_create_account_form, name="create_account_admin"),
    path('admin/update/profile/<int:id>/', views.pri_admin_update_profile, name='admin_update_profile'),
    path('admin/delete/profile/<int:id>/', views.pri_admin_users_delete_form, name='delete_account_admin'),

    #PRI Admin Clients
    path('admin/clients/create/client/', views.pri_admin_create_clients, name="create_clients"),
    path('admin/clients/edit/client/<int:id>/', views.pri_admin_edit_clients, name="edit_clients"),
    path('admin/clients/delete/client/<int:id>/', views.pri_admin_delete_clients, name="delete_clients"),

    path('admin/clients/sort_clients/', views.pri_admin_client_sort_records, name='sort_clients'),
    path('admin/clients/record_limit_clients/', views.pri_admin_client_record_limiter, name="record_limit_clients"),
    path('admin/clients/search_clients/', views.pri_admin_client_search_filter, name="search_clients"),
    path('admin/clients/paging_clients/', views.pri_admin_client_paging, name="paging_clients"),

    #PRI Admin Request
    path('admin/requests/create/requests/', views.pri_admin_create_requests, name="create_requests"),
    path('admin/requests/edit/requests/<int:id>/', views.pri_admin_edit_requests, name="edit_requests"),
    path('admin/requests/delete/requests/<int:id>/', views.pri_admin_delete_requests, name="delete_requests"),
    path('admin/requests/view/requests/<int:id>/', views.pri_admin_view_requests, name="view_requests"),

    path('admin/requests/sort_requests/', views.pri_admin_requests_sort_records, name='sort_requests'),
    path('admin/requests/record_limit_requests/', views.pri_admin_requests_record_limiter, name="record_limit_requests"),
    path('admin/requests/search_requests/', views.pri_admin_requests_search_filter, name="search_requests"),
    path('admin/requests/paging_requests/', views.pri_admin_requests_paging, name="paging_requests"),

    #PRI Admin Jobs
    path('admin/jobs/create/jobs/<int:id>/', views.pri_admin_create_jobs, name="create_jobs"),
    path('admin/jobs/edit/jobs/<int:id>/', views.pri_admin_edit_jobs, name="edit_jobs"),
    path('admin/jobs/delete/jobs/<int:id>/', views.pri_admin_delete_jobs, name="delete_jobs"),

    path('admin/jobs/sort_jobs/', views.pri_admin_jobs_sort_records, name='sort_jobs'),
    path('admin/jobs/record_limit_jobs/', views.pri_admin_jobs_record_limiter, name="record_limit_jobs"),
    path('admin/jobs/search_jobs/', views.pri_admin_jobs_search_filter, name="search_jobs"),
    path('admin/jobs/paging_jobs/', views.pri_admin_jobs_paging, name="paging_jobs"),

    path('admin/jobs/applicant/<str:key>/', views.PriJobsApplicantsRequests.as_view(), name="applicant_request_jobs"),
    path('admin/jobs/applicant/profile/view/<int:id>/<str:akey>/', views.pri_applicant_profile_view, name="applicant_profile_viewer"),

    #toggle exam
    path('admin/jobs/applicant/exam/<str:key>/<int:id>/', views.pri_jobs_applicant_requests_toggle_exam, name="applicant_request_jobs_toggle_exams"),
    #schedules
    path('admin/jobs/applicant/interview/schedule/<str:key>/<int:id>/', views.pri_jobs_applicant_requests_set_interview_sched, name="applicant_request_jobs_set_interview_sched"),

    #PRI Schedules
    path('admin/schedules/job/request/applicant/toggleexam/<int:id>/', views.pri_schedules_toggle_exam, name="toggle_exams"),

    #PRI Applcaints
    path('admin/applicants/registered/delete/<str:key>/', views.pri_admin_delete_applicants, name="applicant_delete_record"),

    path('admin/applicants/job/request/exam/list/<str:key>/<int:id>/', views.PRIApplicantExamListPage.as_view(), name="applicant_exam_list"),
    path('admin/applicants/job/request/exam/test1/pre_employment/<str:key>/<int:id>/', views.pri_applicant_test1_pre_employment, name="applicant_exam_test1"),
    path('admin/applicants/job/request/exam/test2/simple_english/<str:key>/<int:id>/', views.pri_applicant_test2_simple_english, name="applicant_exam_test2"),
    path('admin/applicants/job/request/exam/test3/essay/<str:key>/<int:id>/', views.pri_applicant_test3_essay, name="applicant_exam_test3"),
    path('admin/applicants/job/request/exam/test3/sct/<str:key>/<int:id>/', views.pri_applicant_test3_sct, name="applicant_exam_test3_sct"),
    path('admin/applicants/job/request/exam/test4/abstract_reasoning/<str:key>/<int:id>/', views.pri_applicant_test4_abstract_reasoning, name="applicant_exam_test4"),
    path('admin/applicants/job/request/exam/ssct/<str:key>/<int:id>/', views.pri_applicant_exam_ssct, name="applicant_exam_scct"),
    path('admin/applicants/job/request/exam/ccat/<str:key>/<int:id>/', views.pri_applicant_exam_ccat, name="applicant_exam_ccat"),
    path('admin/applicants/job/request/exam/arp/<str:key>/<int:id>/', views.pri_applicant_exam_arp, name="applicant_exam_arp"),
    #PRI Applicant Examinations
]

pri_online_recruitment_system/pri_online_recruitment_system/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from pors_app import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('pri_administrator/login/', views.pri_user_login, name="user_login"),
    path('pri_administrator/logout/', auth_views.LogoutView.as_view(), name="logout"),

    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    #FOR APPLICANT SIDE
    path('pri/applicant_side/account/registration', views.pri_applicant_account_registration_page, name='applicant_side_account_registration'),
    path('pri/applicant_side/registration/<str:slug>/', views.pri_applicant_registration_page, name='applicant_side_registration'),
    path('pri/applicant_side/update/profile/<str:slug>/', views.pri_applicant_edit_profile_page, name='applicant_side_update_profile'),
    
    path('pri/applicant_side/job/posts/all/', views.PRIApplicantSideJobPostPageAll.as_view(), name='applicant_side_job_posts_all'),
    path('pri/applicant_side/job/posts/recommended/', views.PRIApplicantSideJobPostPageRecommended.as_view(), name='applicant_side_job_posts_recommended'),
    path('pri/applicant_side/job/posts/search/results/', views.PRIApplicantSideJobPostSearchPage, name='applicant_side_job_posts_search'),
    path('pri/applicant_side/job/posts/request/<int:jv_id>/<int:a_id>/', views.pri_applicant_job_request, name='applicant_side_job_request'),
    path('pri/applicant_side/job/applicant/request/status/ongoing/<int:id>/', views.pri_applicant_job_request_ongoing_status, name='applicant_side_job_request_ongoing_status'),

    path('export/csv/', views.export_users_csv, name="export_users_csv"),
    path('export/xls/', views.export_users_xls, name="export_users_xls"),
    path('export/xlsx/', views.export_users_xlsx, name="export_users_xlsx"),

    path('', include('pors_app.urls')),
    path('admin/', admin.site.urls),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#use to access files and images in static

pri_online_recruitment_system/pors_app/templates/pri_admin/pri_admin_admin_page.html
{% extends 'pri_admin/pri_admin_index.html' %}

{% block inner_body %}
<!-- Breadcrumbs-->


<ol class="breadcrumb">
    <li class="breadcrumb-item active">Admin Page</li>
</ol>


<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Users Table
    </div>
    <div class="card-body">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <!-- Navbar Search -->

           <form method="POST" id="form-search-admin"> <!--class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" -->
                <div class="input-group">
                    <input id="search-admin" type="text" class="form-control" placeholder="Search for..." aria-label="Search"
                           aria-describedby="basic-addon2" required>
                    <div class="input-group-append">
                        <button class="btn btn-success btn-search-admin" type="button">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <form style="width: 50%">
                 <div class="input-group">
                       <select class="form-control" id="record-limit-admin" style="width: 15%">
                            <option disabled selected hidden>Show Limit</option>
                            <option>10</option>
                            <option>15</option>
                            <option>25</option>
                            <option>50</option>
                            <option>100</option>
                        </select>
                     <select class="form-control" id="column-admin">
                            <option disabled selected hidden>Sort by</option>
                         {% for col in columns %}
                         <option>{{ col|title }}</option>
                         {% endfor %}
                        </select>
                    <select class="form-control" id="sort-order-admin" style="width: 15%">
                            <option>Descending</option>
                            <option>Ascending</option>
                    </select>

                    <div class="input-group-append">
                        <button class="btn btn-success" type="button" id="button-sort-admin">
                            <i class="fas fa-sort"></i>
                        </button>
                    </div>


                </div>
            </form>

            <button type="button" data-url="{% url 'pri:create_account_admin' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm show-form-create-admin">
                <span class="fas fa-plus fa-sm text-white-50"></span>
                Create new account
            </button>

        </div>

        <div class="table-responsive" id="table_admin">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" style="font-family: candara; font-size: 15px">
                <thead>
                <tr>
                    <th style="width: 5%" class="text-center">ID</th>
                    <th style="width: 10%"  class="text-center">Picture</th>
                    <th style="width: 25%"  class="text-center">Name</th>
                    <th style="width: 15%"  class="text-center">Email</th>
                    <th style="width: 10%"  class="text-center">Contact</th>
                    <th style="width: 10%"  class="text-center">Position</th>
                    <th style="width: 10%"  class="text-center">Department</th>
                    <th style="width: 10%"  class="text-center">Level</th>
                    <th style="width: 15%"  style="width: 200px" class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                    {% include 'pri_admin/tables/pri_admin_users_table.html' %}
                </tbody>
            </table>
        </div>

        <div id="pagination_admin" class="text-center">
            {% include 'pri_admin/paginators/pri_admin_users_pagination.html' %}
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<p class="small text-center text-muted my-5">
    <em>To God be the Glory</em>
</p>

{% endblock inner_body %}

pri_online_recruitment_system/pors_app/templates/pri_admin/pri_admin_applicants_page.html
{% extends 'pri_admin/pri_admin_index.html' %}
{% load staticfiles %}
{% block inner_body %}
<!-- Breadcrumbs-->


<ol class="breadcrumb">
    <li class="breadcrumb-item active">Applicants Page</li>
</ol>


<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Registered Applicants</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered text-center" id="applicantDataTable" width="100%" cellspacing="0" style="font-family: candara; font-size: 15px">
                <thead>
                    <tr>
                        <th style="width: 10%;">Picture</th>
                        <th style="width: 20%;">Username</th>
                        <th style="width: 25%;">Name</th>
                        <th style="width: 5%;">Resume/C.V.</th>
                        <th style="width: 15%;">Mobile No</th>
                        <th style="width: 20%;">Email</th>
                        <th style="width: 15%;">Actions</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Picture</th>
                        <th>Username</th>
                        <th>Name</th>
                        <th>Resume/C.V.</th>
                        <th>Mobile No</th>
                        <th>Email</th>
                        <th>Actions</th>
                    </tr>
                </tfoot>
                <tbody>
                   {% include 'pri_admin/tables/pri_admin_applicants_table.html' %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<p class="small text-center text-muted my-5">
    <em>To God be the Glory</em>
</p>

{% endblock inner_body %}

pri_online_recruitment_system/pors_app/templates/pri_admin/pri_admin_applicants_page_backup.html
{% extends 'pri_admin/pri_admin_index.html' %}

{% block inner_body %}
<!-- Breadcrumbs-->


<ol class="breadcrumb">
    <li class="breadcrumb-item active">Admin Page</li>
</ol>


<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Users Table
    </div>
    <div class="card-body">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <!-- Navbar Search -->

           <form method="POST" id="form-search-admin"> <!--class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" -->
                <div class="input-group">
                    <input id="search-admin" type="text" class="form-control" placeholder="Search for..." aria-label="Search"
                           aria-describedby="basic-addon2" required>
                    <div class="input-group-append">
                        <button class="btn btn-success btn-search-admin" type="button">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <form style="width: 50%">
                 <div class="input-group">
                       <select class="form-control" id="record-limit-admin" style="width: 15%">
                            <option disabled selected hidden>Show Limit</option>
                            <option>10</option>
                            <option>15</option>
                            <option>25</option>
                            <option>50</option>
                            <option>100</option>
                        </select>
                     <select class="form-control" id="column-admin">
                            <option disabled selected hidden>Sort by</option>
                         {% for col in columns %}
                         <option>{{ col|title }}</option>
                         {% endfor %}
                        </select>
                    <select class="form-control" id="sort-order-admin" style="width: 15%">
                            <option>Descending</option>
                            <option>Ascending</option>
                    </select>

                    <div class="input-group-append">
                        <button class="btn btn-success" type="button" id="button-sort-admin">
                            <i class="fas fa-sort"></i>
                        </button>
                    </div>


                </div>
            </form>

            <button type="button" data-url="#" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm show-form-create-admin">
                <span class="fas fa-plus fa-sm text-white-50"></span>
                Create new account
            </button>

        </div>

        <div class="table-responsive" id="table_admin">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Picture</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Contact</th>
                    <th>Position</th>
                    <th>Department</th>
                    <th style="width: 200px" class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>

        <div id="pagination_admin" class="text-center">
        </div>

        
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<p class="small text-center text-muted my-5">
    <em>To God be the Glory</em>
</p>

{% endblock inner_body %}

pri_online_recruitment_system/pors_app/templates/pri_admin/pri_admin_clients_page.html
{% extends 'pri_admin/pri_admin_index.html' %}

{% block inner_body %}
<!-- Breadcrumbs-->


<ol class="breadcrumb">
    <li class="breadcrumb-item active">Client Page</li>
</ol>


<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Clients Table
    </div>
    <div class="card-body">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <!-- Navbar Search -->

           <form method="POST" id="form-search-client"> <!--class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" -->
                <div class="input-group">
                    <input id="search-client" type="text" class="form-control" placeholder="Search for..." aria-label="Search"
                           aria-describedby="basic-addon2" required>
                    <div class="input-group-append">
                        <button class="btn btn-success btn-search-client" type="button">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <form style="width: 50%">
                 <div class="input-group">
                       <select class="form-control" id="record-limit-client" style="width: 10%">
                            <option disabled selected hidden>Show Limit</option>
                            <option>10</option>
                            <option>15</option>
                            <option>25</option>
                            <option>50</option>
                            <option>100</option>
                        </select>
                     <select class="form-control" id="column-client" style="width: 20%">
                            <option disabled selected hidden>Sort by</option>
                         {% for col in columns %}
                         <option>{{ col|title }}</option>
                         {% endfor %}
                        </select>
                    <select class="form-control" id="sort-order-client" style="width: 10%">
                            <option>Descending</option>
                            <option>Ascending</option>
                    </select>

                    <div class="input-group-append">
                        <button class="btn btn-success" type="button" id="button-sort-client">
                            <i class="fas fa-sort"></i>
                        </button>
                    </div>


                </div>
            </form>

            <button type="button" data-url="{% url 'pri:create_clients' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm show-form-create-client">
                <span class="fas fa-plus fa-sm text-white-50"></span>
                Create new client
            </button>

        </div>

        <div class="table-responsive" id="table-client">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" style="font-family: candara; font-size: 15px">
                <thead>
                <tr>
                    <th style="width: 5%" class="text-center">ID</th>
                    <th style="width: 20%" class="text-center">Logo</th>
                    <th style="width: 20%" class="text-center">Company</th>
                    <th style="width: 20%" class="text-center">Client Name</th>
                    <th style="width: 20%" class="text-center">Location</th>
                    <th style="width: 15%" class="text-center">Contact Person</th>
                    <th style="width: 15%" class="text-center">Mobile</th>
                    <th style="width: 20%" class="text-center">Email</th>
                    <th style="width: 5%" class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% include 'pri_admin/tables/pri_admin_clients_table.html' %}
                </tbody>
            </table>
        </div>

        <div id="pagination-client" class="text-center">
            {% include 'pri_admin/paginators/pri_admin_users_pagination.html' %}
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<p class="small text-center text-muted my-5">
    <em>To God be the Glory</em>
</p>

{% endblock inner_body %}

pri_online_recruitment_system/pors_app/templates/pri_admin/pri_admin_jobs_applicants_page.html
{% extends 'pri_admin/pri_admin_index.html' %}

{% block inner_body %}
<!-- Breadcrumbs-->


<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="{% url 'pri:jobs' %}">Jobs vacancies page</a>
  </li>
  <li class="breadcrumb-item active">{{job_vacancies.client_request.requested_client.client_company_name }}</li>
  <li class="breadcrumb-item active">{{ job_vacancies.job_title }}</li>
  
</ol>

<!-- Data Tables -->

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Requesting Applicants</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered text-center" id="jobRequestApplicantsDataTable" width="100%" cellspacing="0" style="font-family: candara; font-size: 15px">
                <thead>
                    <tr>
                        <th style="width: 10%;">Picture</th>
                        <th style="width: 20%;">Name</th>
                        <th style="width: 5%;">Resume/C.V.</th>
                        <th style="width: 10%;">Mobile #</th>
                        <th style="width: 10%;">Email</th>
                        <th style="width: 5%;">Status</th>
                        <th style="width: 15%;">Date Applied</th>
                        <th style="width: 5%;">Exam</th>
                        <th style="width: 20%;">Interview Date</th> 
                    </tr>
                </thead>
                <tfoot> 
                </tfoot>
                <tbody>
                    {% include 'pri_admin/tables/pri_admin_jobs_applicant_request_table.html' %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<p class="small text-center text-muted my-5">
  <em>To God be the Glory</em>
</p>

{% endblock inner_body %} 

pri_online_recruitment_system/pors_app/templates/pri_admin/pri_admin_requests.html
{% extends 'pri_admin/pri_admin_index.html' %}

{% block inner_body %}
<!-- Breadcrumbs-->

<style>
 td {
    max-width: 100px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
</style>

<ol class="breadcrumb">
    <li class="breadcrumb-item active">Request Page</li>
</ol>


<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Request Table
    </div>
    <div class="card-body">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <!-- Navbar Search -->

           <form method="POST" id="form-search-requests"> <!--class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" -->
                <div class="input-group">
                    <input id="search-requests" type="text" class="form-control" placeholder="Search for..." aria-label="Search"
                           aria-describedby="basic-addon2" required>
                    <div class="input-group-append">
                        <button class="btn btn-success btn-search-requests" type="button">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <form style="width: 50%">
                 <div class="input-group">
                       <select class="form-control" id="record-limit-requests" style="width: 10%">
                            <option disabled selected hidden>Show Limit</option>
                            <option>10</option>
                            <option>15</option>
                            <option>25</option>
                            <option>50</option>
                            <option>100</option>
                        </select>
                     <select class="form-control" id="column-requests" style="width: 20%">
                            <option disabled selected hidden>Sort by</option>
                         {% for col in columns %}
                         <option>{{ col|title }}</option>
                         {% endfor %}
                        </select>
                    <select class="form-control" id="sort-order-requests" style="width: 10%">
                            <option>Descending</option>
                            <option>Ascending</option>
                    </select>

                    <div class="input-group-append">
                        <button class="btn btn-success" type="button" id="button-sort-requests">
                            <i class="fas fa-sort"></i>
                        </button>
                    </div>


                </div>
            </form>

            <button type="button" data-url="{% url 'pri:create_requests' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm show-form-create-requests">
                <span class="fas fa-plus fa-sm text-white-50"></span>
                Create new client request
            </button>

        </div>

        <div class="table-responsive" id="table-requests">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" style="font-family: candara; font-size: 15px;">
                <thead>
                <tr>
                    <th style="width: 5%" class="text-center">ID</th>
                    <th style="width: 15%" class="text-center">Client</th>
                    <th style="width: 30%" class="text-center">Content</th>
                    <th style="width: 10%" class="text-center">Status</th>
                    <th style="width: 18%" class="text-center">Date Requested</th>
                    <th style="width: 12%" class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% include 'pri_admin/tables/pri_admin_requests_table.html' %}
                </tbody>
            </table>
        </div>

        <div id="pagination-requests" class="text-center">
            {% include 'pri_admin/paginators/pri_admin_users_pagination.html' %}
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<p class="small text-center text-muted my-5">
    <em>To God be the Glory</em>
</p>

{% endblock inner_body %}